[package]
name = "practice"
version = "0.1.0"
authors = ["zrma <bulbitain@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
csv = "1.1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
